### ISSUE TITLE
Show multiple balloons in sequence in recycler view

### ISSUE THREAD

**Issue by vkhirani93** [skydoves/Balloon#230]
In case of sequential balloons inside a fragment/activity, we use relayShow() but how do we achieve this when we want to show balloon in sequence for multiple recycler view items. Is this possible? 

I read the documentation but didn't find anything related to it.

 Please help. Thanks in advance.

**Comment by skydoves** [comment]
Hi @vkhirani93, could you explain more details?
I think you can achieve this using like `onItemClickListener(itemAnchorView: View, data: Any)` and passing the item View to the listener.

**Comment by vkhirani93** [comment]
Hi @skydoves,
I have a RecyclerView with a Grid Adapter. I want to show balloon as a tooltip for few items in order to highlight them.

For e.g. If I have 12 items in the 3 X 4 Grid. I want to show balloon over 1st item, 5th item and 8th item one-by-one after a specific time interval (Let us consider 5 sec.). 

The balloon over the 1st item should be dismissed automatically after 5 seconds and then it should be shown over the 5th item thereafter. Similarly the balloon over the 5th item in the grid should be dismissed automatically after 5 seconds and then it should be shown over the 8th item.

Can I achieve this currently using the library? If yes, please explain. If no, can you please consider taking this as a feature request?

PS: After evaluating more than 10 libraries, I feel yours is truly great. Great work!!!

**Comment by skydoves** [comment]
Hi @vkhirani93, sorry for the late reply.
Hmm, that's interesting. There is no clear solution to implement it, but I guess you can implement it manually using the Balloon.
Firstly, you can show up balloon [sequentially](https://github.com/skydoves/balloon#show-sequentially) using `relayShow` methods. So initialize multiple balloons that should be shown on your Activity or Fragment instead of on your ViewHolder.
Here are some tricky ways to show up Balloon over your RecyclerView's item. 
- Hold some instances of the `View` on your RecyclerView such as 1st and 5th and 8th in a list. And show up the balloon based on the anchor `View`.
- Just show up your balloon based on the position of items on your RecyclerView using `showAsDropDown`. You can reference [this](https://stackoverflow.com/questions/38004369/get-x-y-positions-of-nth-item-in-recyclerview) for getting each position of the item on your RecyclerView. The anchor view should be the root view of your Activity or Fragment.

I hope these solutions could be helpful!
