### ISSUE TITLE
Tooltips inside when recycler view cell goes out of viewport

### ISSUE THREAD

**Issue by i-schuetz** [skydoves/Balloon#26]
**Please complete the following information:**
- Library Version 1.1.2
- Affected Device(s) Emulator

When I open a tooltip inside a recycler view cell and scroll such that the cell goes outside the view port, the tooltip stays inside (at the edge). This looks weird as it's not pointing to anything anymore. 

Is it possible to make it go out of the screen together with the cell (and back in)?

Settings
```kotlin
setArrowSize(10)
//        setWidthRatio(1.0f)
setHeight(65)
setPadding(0)
//        setDismissWhenTouchOutside(true)
setPaddingLeft(10)
setPaddingRight(10)
//        setArrowPosition(.5f)
setSpace(10)
setCornerRadius(10f)
setAlpha(1f)
setTextColorResource(R.color.white)
setBackgroundColorResource(R.color.colorAccent)
setOnBalloonClickListener {
    onClick?.invoke()
}
setBalloonAnimation(BalloonAnimation.ELASTIC)
setLifecycleOwner(lifecycleOwner)
```

Note that `setDismissWhenTouchOutside` is commented. I don't want the tooltips to disappear immediately.

<img width="391" alt="Screen Shot 2020-03-24 at 16 05 16" src="https://user-images.githubusercontent.com/1381744/77441054-49baae00-6de9-11ea-9291-83b0c54dc259.png">

The tooltip showing in the screenshot belongs to an item that's outside (top) of the screen.

**Comment by skydoves** [comment]
It seems related to this [issue](https://github.com/skydoves/PowerMenu/issues/58) from the usage of popupwindow. I will check out it soon usage in the RecyclerView.

**Comment by i-schuetz** [comment]
Hi @skydoves thanks for your quick replies. I just wanted to ask if you think all the issues can be realistically fixed soon? Or do you have maybe any indicators for me to try to fix? We have a bit of time pressure.

**Comment by skydoves** [comment]
Hi, I've been thinking about this for some days, but there is no way to resolve this problem.
The concept of the window is an abstract base class for a top-level window look and behavior policy. So the window is never subordinated by views. You can use the balloon instead of the [ContextMenu](https://developer.android.com/reference/android/view/ContextMenu).
More lightweight and fully customizable with animation.
So the best case is, use with the `setDismissWhenTouchOutside` or call `dismiss` manually when the recyclerView is scrolled. Anyway, thank you for your issue :)

**Comment by i-schuetz** [comment]
Makes sense.
