### ISSUE TITLE
Animation is not working in Android 11 lib latest version on Redmi 11 pro 

### ISSUE THREAD

**Issue by kushaldhengole** [skydoves/Balloon#364]
**Please complete the following information:**
- Library Version [e.g. v1.0.0]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 
**Describe the Bug:**

Add a clear description about the problem.

**Expected Behavior:**

A clear description of what you expected to happen.

**Comment by kushaldhengole** [comment]
Balloon animation is not working for Redmi Note Pro 11

**Comment by skydoves** [comment]
Hi, could you elaborate on which animation is not working? Thanks!

**Comment by kushaldhengole** [comment]
thank for responses .
BalloonAnimation's All Animation  are not working 
this below line is added but it not giving animation 
  .setBalloonAnimation(BalloonAnimation.ELASTIC)

**Comment by kushaldhengole** [comment]
code working in other device with  android 11 . But in  Redmi Note pro+ 5G  with android 11 it's not working

**Comment by skydoves** [comment]
I'm not really sure this issue is related to the library, because all of the animations are based on Android systems. Could you please check device's animation setup is normal in the developer options?

![Screen Shot 2022-09-17 at 11 21 03 PM](https://user-images.githubusercontent.com/24237865/190861830-e9067f27-866e-44c9-8c5f-08fe80082005.png)

**Comment by kushaldhengole** [comment]
Thank you  for information .
issue is with device setting and it resolved  now
