### ISSUE TITLE
the arrow does not follow the image

### ISSUE THREAD

**Issue by dvasundhara** [skydoves/Balloon#43]
**Please complete the following information:**
- Library Version [e.g. v1.1.5]
- Affected Device(s) [e.g. Samsung Galaxy s10 with Android 9.0]
 all devices
**Describe the Bug:**
When the image for which the tooltip is attached , is moved . the ballon arrow do not follow the image. 
For example: on the toolbar with chrome cast icon and without chrome cast icon , my image moves left to chrome cast icon or towards end of the toolbar. The arrow of the balloon meaning the ballon do not take position with respect to image.
my settings in the factory are 
setArrowSize(10)
            setArrowPosition(0.83f)
            setArrowVisible(true)
            setWidthRatio(0.90f)
            setCornerRadius(8f)
            setTextForm(textForm)
            setArrowOrientation(ArrowOrientation.TOP)
            setBackgroundColorResource(R.color.accent)
            isRtlSupport(true)

**Expected Behavior:**
I would expect the ballon should move according to the position of the 
<img width="409" alt="clip of TT" src="https://user-images.githubusercontent.com/5472322/80849195-f64b3500-8bca-11ea-8a7a-f89e35d8fe9b.png">
<img width="396" alt="clip2" src="https://user-images.githubusercontent.com/5472322/80849197-fc411600-8bca-11ea-8768-59071cd1dffa.png">

assigned image.
A clear description of what you expected to happen.

**Comment by skydoves** [comment]
Hi, thank you for your issue.
Unfortunately, this issue cant not be resolved until Google releases a new SDK related to PopupWindow.

Once a pop-up window inflated and showed on the screen, it can not be re-inflated. Because the popup window could be created only already inflated layout, and android SDK doesn't support recreating and reinflating methods.

So the only solution is dismissing and showing again.
