### ISSUE TITLE
Working with ImageSpan

### ISSUE THREAD

**Issue by green985** [skydoves/Balloon#541]
**Is your feature request related to a problem?**

A clear and concise description of what the problem is.

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

A clear description of any alternative solutions you've considered.

I would like to make ImageSpan and ClickableSpan and using this balloon to show some description to users.
My problem is, imageSpan doesn't provide any view or similar variable. 

Is there any recommendation about this problem ? 
Ps: Already try offset but could find any decent solution.

**Comment by skydoves** [comment]
Hey @green985, would you elaborate on your issue?

**Comment by green985** [comment]
My bad, let me explain better. 

I am working with text view include some imageSpan in this textview.  I want to develop, when I click the image span, I want to open your balloon dialog for the describe some word or etc. 

I am using showAtCenter func with offsets.

calculate offsetX  = clickX position - pivotX position of view 
calculate offsetY =  clickY position - pivotY position of view 

![image](https://github.com/skydoves/Balloon/assets/13219237/22ef528b-200d-4c3a-b42d-6f4ce9d456a6)

If imageSpan near to center or not connected with right left end area, result is quite good. 

but if description open position near to left or right, arrow position not fit to exact position of imageSpan.

![image](https://github.com/skydoves/Balloon/assets/13219237/227eb36d-adfb-4a73-a15f-3a1c97db63ce)

I tried to change orientation properties such as setArrowOrientation or position rules setArrowPositionRules but couldn't find decent solution. 
 ```
val balloon = Balloon.Builder(baseFragment.requireContext())
            .setWidthRatio(0.4f)
            .setLayout(R.layout.custom_verse_note_balloon_view)
            .setHeight(BalloonSizeSpec.WRAP)
            .setTextSize(15f)
            .setArrowPositionRules(ArrowPositionRules.ALIGN_BALLOON)
            .setArrowOrientation(ArrowOrientation.BOTTOM)
            .setArrowSize(10)
            .setArrowColor(baseFragment.requireContext().getColorFromAttr(R.attr.coloredTextColor))
            .setBackgroundDrawableResource(R.drawable.bg_rounded_app_background)
            .setArrowPosition(0.5f)
            .setCornerRadius(8f)
            .setBackgroundColorResource(R.color.transparent)
            .setBalloonAnimation(BalloonAnimation.OVERSHOOT)
            .setLifecycleOwner(baseFragment.viewLifecycleOwner)
            .build()
 ```


Right now, I used this properties for build balloon object. 

Thank you.

**Comment by nkhar** [comment]
Hello @green985 

If by ImageSpan you mean scope icon, then I might be able to help. What you need is to align arrow to the anchor.
By default arrow is aligned to the centre of ballon itself. This is caused because of the rule `ArrowPositionRules.ALIGN_BALLOON` and by this parameter: `public var arrowPosition: Float = 0.5f`

I think what you need is to align the arrow to the image instead of balloon so instead of
`.setArrowPositionRules(ArrowPositionRules.ALIGN_BALLOON)`
try this
`.setArrowPositionRules(ArrowPositionRules.ALIGN_ANCHOR)`

**Comment by green985** [comment]
Hello again, 
I already did your recommendation and It didnt work. 

So I did different kind of approach. 

I created empty view which has a 1dp width 1dp height and transparent.
I found my every Imagespan object location (added location to textview) and move transparent  imageView to this location just before the balloon show function. I know this is not best solution it works. 

I hope this library can provide open balloon without view just exact location. 
Thank you for this great library.

**Comment by nkhar** [comment]
Hello @green985 thank you for your feedback,
I am not sure I understand your requirements. Can you give us some sample code that shows your problem and another sample that shows how you solved it?

Previously you provided only ballon Builder code, without the part that shows its usage.

> val balloon = Balloon.Builder(baseFragment.requireContext())
>            .setWidthRatio(0.4f)
>            .setLayout(R.layout.custom_verse_note_balloon_view)
>            .setHeight(BalloonSizeSpec.WRAP)
>            .setTextSize(15f)
>            .setArrowPositionRules(ArrowPositionRules.ALIGN_BALLOON)
>            .setArrowOrientation(ArrowOrientation.BOTTOM)
>            .setArrowSize(10)
>            .setArrowColor(baseFragment.requireContext().getColorFromAttr(R.attr.coloredTextColor))
>            .setBackgroundDrawableResource(R.drawable.bg_rounded_app_background)
>            .setArrowPosition(0.5f)
>            .setCornerRadius(8f)
>            .setBackgroundColorResource(R.color.transparent)
>            .setBalloonAnimation(BalloonAnimation.OVERSHOOT)
>            .setLifecycleOwner(baseFragment.viewLifecycleOwner)
>            .build()

**Comment by skydoves** [comment]
@nkhar Thanks for your response on this! 

@green985 Hmm, I hadn't considered these use cases before. However, it appears to be the only feasible solution to this issue at the moment. Since the `ImageSpan` cannot function as an anchor view by itself, creating a mock view instance to display the balloon seems to be the only viable approach currently. 

But at the same time, adding a non-generic feature to support only the composition of the ImageSpan and TextView can harm the entire purpose of this library, so I don't have any plans for supporting it directly right now. If I find a better approach, I will definitely let you share the solution!

Thank you guys for reporting & suggesting this issue!
