### ISSUE TITLE
Height not correct when inflating custom layout

### ISSUE THREAD

**Issue by robertodries92** [skydoves/Balloon#55]
**Please complete the following information:**
- Library Version [e.g. v1.1.7]
 
**Describe the Bug:**

After inflating a custom layout with several text fields the height is not correctly set.

```
      val balloon = createBalloon(context) {
            setLayout(R.layout.onboarding_tour_dialog)
      }

      val contentView = balloon.getContentView()
      // set the correct text
   

      balloon.showAlignTop(targetView)
     
```
![image](https://user-images.githubusercontent.com/3204626/83153418-37b5fe00-a0ff-11ea-8f3e-672a29b9eb2e.png)

**Expected Behavior:**

The height is correctly calculated.

![image](https://user-images.githubusercontent.com/3204626/83153237-050c0580-a0ff-11ea-9210-fcc95cc5c6b6.png)

**Comment by skydoves** [comment]
Hi, thank you for your issue.
Actually it is an expected result.

The measuring size of the `textView` is difficult because it is changed by every device's size of letters and languages or other environments. So If we want to get the exact size of the width/height of the textView, the textView must be inflated completely. 

So `PopupWindow` can't know the exact size of the textView. Because the layout will be inflated after showing up the `PopupWindow`. (The layout will be inflated on the `PopupWindow`.)

Fortunately, we can calculate the exact width/height size of the textView if we know the height/width size oppositely. So the basic form of the balloon (with icon and on textView) can be calculated exact height size because we know the width size of the Balloon.

Also, we can measure the exact height size of the customized popup if we know the exact width size. And there are some solutions.

#### 1. Use fixed width/height size of the custom layout
```gradle
android:layout_width="240dp"
android:layout_height="wrap_content"
```
or (not recommended)
```gradle
android:layout_width="wrap_content"
android:layout_height="240dp"
```

#### 2. Use maxWidth
By using the `maxWidth` attribute, the height size of the popup can be measured exactly.
```gradle
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:gravity="center"
  android:orientation="vertical"
  android:padding="12dp">

  <TextView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:maxWidth="240dp"
    ...
```
