### ISSUE TITLE
Arrow does not show elevation

### ISSUE THREAD

**Issue by sharvaniharan** [skydoves/Balloon#76]
**Please complete the following information:**
- Library Version v1.1.9
- Affected Device(s) - all devices
 
**Describe the Bug:**

When an elevation is defined on the bubble, the arrow seems to not pick up the elevation.
**Expected Behavior:**

Arrow has the same elevation as the bubble.

**Comment by skydoves** [comment]
Hi, @sharvaniharan!
Thank you for your issue.
The problem is the arrow is an ImageView, but it must have a transparent background.
But the elevation can be shown If the view has a colored background.
I will consider implementing an ArrowDrawable and drawing shadow manually.
If you have any good suggestions, let me know your idea!

**Comment by skydoves** [comment]
It has been released a new version [1.3.1](https://github.com/skydoves/Balloon/releases/tag/1.3.1)!
Please check about this issue :)
