### ISSUE TITLE
onBalloonOutsideTouch() is never called.

### ISSUE THREAD

**Issue by dbrant** [skydoves/Balloon#93]
- Library Version: 1.2.1
- API 29
 
We would like to use the `OnBalloonOutsideTouchListener` callback, but it seems to never get called, regardless of what other options we provide to the Builder -- I've tried `setDismissWhenTouchOutside(true / false)`, `setFocusable(true / false)`, etc.

**Comment by monisany** [comment]
- Library Version: 1.2.4

Hi,
I have a similar problem with `OnBalloonOutsideTouchListener` callback. It is called only when I don't set `setDismissWhenTouchOutside(false)`. But I have to set `setDismissWhenTouchOutside(false)` because I don't want balloon to disappear after outside touch. I want to handle outside touch myself (do some other logic), but also prevent balloon from dismissing after outside touch. How can I do that?
I tried library version 1.1.6 (based on your advice here https://github.com/skydoves/Balloon/issues/53) and it works as expected. I can set `setDismissWhenTouchOutside(false)` and also get `OnBalloonOutsideTouchListener` callback. Seems like bug in newer version(s)? 
Thanks.

**Comment by skydoves** [comment]
Hi, @monisany.

It seems confusing to use "setDismissWhenTouchOutside" because many other functions are related.
The interface will change not to close a popup to the default setting if we use the `OnBalloonOutsideTouchListener` in the next release. Thank you!

**Comment by skydoves** [comment]
@monisany @dbrant 
It is released in the new version [1.2.5`](https://github.com/skydoves/Balloon/releases).
Thanks for reminding this issue!
