### ISSUE TITLE
Facebook similar react popover

### ISSUE THREAD

**Issue by BoumBam** [skydoves/Balloon#99]
Is it possible with that library to make something like below:
![119106801_2742095952726640_219138023220960444_n](https://user-images.githubusercontent.com/26336351/93222526-9363d000-f75e-11ea-8440-cab592fc891b.jpg)

??

I have put emojis in my layout file but I can't make the touched image bigger over the popover container.

**Comment by skydoves** [comment]
Hi, @BoumBam 
I've thought about this kind of implementation a few days recently, 
The oversize can be implemented using the `update `function and customized layout (RecyclerView and Cardview inside of a constraintlayout), but how do you think about the action scenarios? (touch-up, expand -> touch-down, collapse then how select one is menu using listeners? because it should be draggable like a Facebook.)

**Comment by skydoves** [comment]
I checked this recently in the Facebook application. But in your example is implemented using React native, not the Android native. On the other hand, Facebook's messenger application used this kind of style for implementing the emoji reaction popup. I can't sure the messenger app was implemented using Android native, but this style is making sense in the native.

![KakaoTalk_20201211_221435507](https://user-images.githubusercontent.com/24237865/101907750-580e5b80-3bfe-11eb-8c9c-262e9672045d.jpg)

I will close this issue, and If you have a better idea for implementing those kinds of examples using the `window`, let me know!
